### ISSUE TITLE
Здравствуйте !

### ISSUE THREAD

**Issue by iyrvar** [Bilaboz/duino-coin-pools#15]
Ошибка компилятора -
/data/data/name.antonsmirnov.android.arduinodroid2/sdkEsp8266/hardware/esp8266/2.7.1/cores/esp8266/Crypto.h:749:7: error: 'br_hkdf_context' in namespace '::' does not name a type
Подскажите далёкому ?
Мне есть смысл двиготся в этом направлении, или это лиш начало терней ?
Esp заливаю с android но ране проблем с этим не было.

**Comment by Bilaboz** [comment]
Hello, this is not the correct repository for this issue, you should ask on [duino-coin ](https://github.com/revoxhere/duino-coin) repo.
