### ISSUE TITLE
How to make pool id?

### ISSUE THREAD

**Issue by MetrisVailore** [Bilaboz/duino-coin-pools#25]

**Comment by Bilaboz** [comment]
You can use the createPool script
https://github.com/Bilaboz/duino-coin-pools/blob/main/utils/createPool.js

**Comment by MetrisVailore** [comment]
I am getting an error on startup - No pool ID

**Comment by MetrisVailore** [comment]
It seems to have solved the problem, but the following appears: **Socket error while syncing: Error: connect ETIMEDOUT 51.15.127.80:443**

**Comment by Bilaboz** [comment]
You cannot create a pool on the official duino-coin network, only trusted people can host one
If you want to experiment with creating a pool you can make your own testnet at home by running all duino-coin services locally

**Comment by MetrisVailore** [comment]
Thank you, then it's clear.
