### ISSUE TITLE
Git hub repository is outdated and not complete!

### ISSUE THREAD

**Issue by UweR70** [Bilaboz/duino-coin-pools#8]
Git hub repository is outdated and not complete!

A) Regarding "outdated":
It seems that 
repository directory "/config"
file "poolRewards.json"
is outdated!

B) Regarding "not complete"
File
https://github.com/Bilaboz/duino-coin-pools/blob/main/src/mining.js
line 97  serverMinersFile = require('../config/serverMiners.json');
Repository directory "/config" does NOT contain the file "serverMiners.json"

What else is outdated or not published/publicly available?

**Comment by Bilaboz** [comment]
Hello, poolRewards.json and serverMiners.json gets updated automatically
https://github.com/Bilaboz/duino-coin-pools/blob/e9aa042a0d14e8d057ad286147b89bd40a78ef3d/src/sync.js#L242
https://github.com/Bilaboz/duino-coin-pools/blob/e9aa042a0d14e8d057ad286147b89bd40a78ef3d/src/sync.js#L271

**Comment by UweR70** [comment]
Please read my issue description careful.
I am talking about the repository.
I am NOT talking about a dynamically generated file.

What about part B)?

**Comment by Bilaboz** [comment]
I just added `serverMiners.json`  in /config so it doesn't throw an error.
Thanks for reporting
