### ISSUE TITLE
Got banned?

### ISSUE THREAD

**Issue by UweR70** [Bilaboz/duino-coin-pools#9]
Get multiple times banned?
No reason displayed, shown nor added to any (api/socket) response!

Background:
I am trying to write my own Duino miner.
What did I wrong?

**Comment by Bilaboz** [comment]
Hello, this is not the correct repository for this issue, you should ask on duino-coin repo.
There is multiple reasons for a temporary ban like submitting a lot of invalid shares, making too many requests to the api, ...

**Comment by UweR70** [comment]
Thanks for your reply. 
Ok. Understood.
